Fix remove from empty collection
When removing documents from empty documents, GroundDB was trying to recover document to remove and raising following error:

TypeError: Cannot read property '_id' of undefined(…) TypeError: Cannot read property '_id' of undefined